### ISSUE TITLE
onWheel of ``useGesture`` throws error "Unable to preventDefault inside passive event listener invocation"

### ISSUE THREAD

**Issue by kousenlsn** [pmndrs/use-gesture#324]
**Describe the bug**
> onWheel of ``useGesture`` throws error "Unable to preventDefault inside passive event listener invocation"

![image](https://user-images.githubusercontent.com/14895129/123560022-32017080-d776-11eb-8ae5-66c1c75a5663.png)

**Information:**
 - React Use Gesture version: [e.g. v10.0.0-beta.14]
 - Device: MacBook pro
 - Browser: Brave, Chrome

**Checklist:**
  - [X] I've read the [documentation](https://use-gesture.netlify.app/).

**Comment by dbismut** [comment]
Should be fixed in 10.0.0-beta.15, let me know!

**Comment by kousenlsn** [comment]
Sorry for the delay, I haven't had much time lately. But it seems it is still occurring

**Comment by dbismut** [comment]
Would it be possible to set up a repro sandbox? Are you sure you've updated to the latest version?

**Comment by kousenlsn** [comment]
Yes, I tried creating a [sandbox](https://codesandbox.io/s/scroll-use-gesturenext-ew2m2) to replicate but it seems to work in it, so I tried adding Next.js, which I'm using, but stills seems to still work, so perhaps it is some other conflict. But I'll try to figure it out here, thanks anyway.

Where the error happens btw:
![image](https://user-images.githubusercontent.com/14895129/124123342-9ad63a80-da4d-11eb-8a4a-1d9168c068f0.png)

**Comment by CodeForcer** [comment]
@dbismut this is still occurring in 2024 with latest version

**Comment by dbismut** [comment]
@CodeForcer is there a way to provide a repro? I'm not sure what more I can do than putting the `preventDefault` inside a `try / catch` block.

**Comment by CodeForcer** [comment]
This isn't breaking any functionality, but it's a bit annoying in browser console. I think the error is being thrown async from the preventDefault inside the package so it's hard to catch.

<img width="356" alt="Screenshot 2024-08-29 at 17 30 07" src="https://github.com/user-attachments/assets/b67d9aa4-22a9-49c4-b8e6-e53616def69d">

Maybe the passive == false from the setting options isn't being propagated into the package? (ie a listener somewhere is being attached with passive == true in the package, regardless of my bindings)

**Comment by CodeForcer** [comment]
Ok I fixed it!

For anyone reading, you need to call useGestures() with a targetRef for the container it should effect, instead of trying to bind on the React component.

**Comment by dbismut** [comment]
Hm if this isn't in the doc than it's an omission, my bad. It's a known fact that you can't `preventDefault` on React's events as they are passive by default. When binding through Reach event handlers with `{...bind()}`, preventDefault won't work. However this is weird that you would see anything showing in the console because of the try / catch.

**Comment by CodeForcer** [comment]
Thank you for the prompt response and maintaining such useful software for free!

**Comment by dbismut** [comment]
I had skipped your comment with the code excerpt above. Ok so maybe I forgot a try / catch there!
